package com.ub.beerOrderService.domain;

public enum BeerOrderStatusEnum {
    NEW,
    VALIDATION_PENDING, VALIDATED, VALIDATION_EXCEPTION,
    ALLOCATION_PENDING, ALLOCATED, ALLOCATED_EXCEPTION,
    PENDING_INVENTORY,
    CANCELLED,
    PICKED_UP,
    DELIVERED, DELIVERY_EXCEPTION
}
